### ISSUE TITLE
메뉴가 정상적으로 나오지 않아요!

### ISSUE THREAD

**Issue by junorouse** [Jinmo/jekyll-casper#1]
https://www.dropbox.com/s/h5ng4g8pb699975/Screenshot%202017-04-20%2017.39.17.png?dl=0

**Comment by Jinmo** [comment]
아, 그건 메뉴가 없어서 그렇습니다. 메뉴도 yaml 형식으로 추가할 수 있게 해야겠군요..!

**Comment by Jinmo** [comment]
이제 나옵니다! :smile:
