### ISSUE TITLE
The HTTP Title displayed on the post page is the blog name in _config.yml

### ISSUE THREAD

**Issue by moonagic** [Jinmo/jekyll-casper#5]
I wanna show post.title
Can you tell me how to do?
Thanks.

**Comment by Jinmo** [comment]
Thanks for the reporting!
I found that the casper theme uses `meta_title` tag for the title, which shows post.title when in post page. Just fixed it in the last commit, thanks! (Also fixed some bugs in author displays.)

**Comment by moonagic** [comment]
Yeah, this commit fix the post title.
But now there was no title in home page.

I am so sorry, I am not a frontend engineer. I can not help you anything..

**Comment by Jinmo** [comment]
No problem since posting issues helps me fix the bugs!

Fixed in local, will upload it after testing.

**Comment by Jinmo** [comment]
Uploaded! Now it shows correct title for posts & main page & authors page.
